export {default as Landing } from "./landingPage"
export {default as Screen2 } from "./screen2"
export {default as Screen3 } from "./screen3"
export {default as Screen4 } from "./screen4"
export {default as Screen5 } from "./screen5"